POST http://localhost:5034/api/v1/Orders/Users/06d3b325-d505-4038-8ee8-f517b1a5216a/Orders
# POST http://localhost:5034/api/v1/products
content-type: application/json

{
  "items": [
    {
      "productId": "4dd60024-77a5-4936-ac7b-b8709d890023",
      "quantity": 2
    },
    {
      "productId": "14c5a173-0ca5-4c02-8754-0776c80a7923",
      "quantity": 5
    }
  ]
}

# {
#   "name": "Nokia 3310",
#   "description": "cassava phone",
#   "price": 508.54,
#   "categoryId": "9ea7a9e7-5546-4f67-806f-27eb3b2858f9",
#   "inventory": 25,
#   "imageUrl": "http://openimages.com/nokia.png"
# }